### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by 841660202** [leanflutter/flutter_flipperkit_examples#1]
操作：
1、将fish_redux_example下载到本地
2、flutter packages get
```xml
// 添加权限
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" ></uses-permission>
<uses-permission android:name="android.permission.INTERNET" ></uses-permission>
```
3、vscode 执行debug

问题：

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51291/iIOhI-zSyA4=/ws
Exited (sigterm)

环境：
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] Connected device (1 available)

```
pubspec.yaml配置
```yaml
name: fish_redux_example
description: Demonstrates how to use the fish_redux.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
    sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
    fish_redux: ^0.2.2
    flutter:
        sdk: flutter
    flutter_flipperkit: ^0.0.15
    flipperkit_fish_redux_middleware: ^0.0.3
    path_provider: ^0.4.1

dev_dependencies:
    test: ^1.3.0
    mockito: ^3.0.0
    flutter_driver:
        sdk: flutter
    flutter_test:
        sdk: flutter
# dependency_overrides:
#   flutter_flipperkit:
#     path: ../../blankapp/flutter_flipperkit
#   flipperkit_fish_redux_middleware:
#     path: ../../blankapp/flutter_flipperkit_plugins/packages/flipperkit_fish_redux_middleware

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the Icons class.
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.io/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.io/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.io/custom-fonts/#from-packages


```
